### PR TITLE
add Toppage

### PR DESCRIPTION
**Pull request by L4Ph**
WIP
and It also includes changes such as code formatting

### CODE REVIEW

**Comment by L4Ph** [comment]
@Kokohachi @Tps-F @p1atdev

**Comment by Kokohachi** [comment]
Conflict; need to fix

**Comment by L4Ph** [comment]
Write権限ないからResolve conflictsできない...

**Comment by Kokohachi** [comment]
おーん

**Comment by Kokohachi** [comment]
@p1atdev @Katsuyuki-Karasawa @Tps-F Add admin

**Comment by Tps-F** [comment]
Thank you!

**Review by Kokohachi — APPROVED** [review]
Nice

**Comment by L4Ph** [comment]
@Kokohachi fix

**Pull request merged**
